### ISSUE TITLE
改用  io.popen("com")      不用等    也不閃屏

### ISSUE THREAD

**Issue by shewer** [amorphobia/openfly#39]
https://github.com/amorphobia/openfly/blob/15fbbbd0a8bd73aa90db0d1b853960d5caba77bc/lua/openfly_shortcut_processor.lua#L66

**Comment by amorphobia** [comment]
我一开始也试过 `io.popen(cmd)`, 依然会有 Command Prompt 闪一下

**Comment by shewer** [comment]
加  start    看看   
"start http://www.google.com"

**Comment by amorphobia** [comment]
首先 `cmd` 的内容本身就是 `start ...`

然后我测试了一下直接把这句改为
```
io.popen("start calc.exe")
```
依然会有 Command Prompt 闪现。

我的系统是 Windows 10 不知是否有关系

**Comment by shewer** [comment]
start /help
開始另一個視窗來執行指定的程式或命令。

START ["title"] [/D path] [/I] [/MIN] [/MAX] [/SEPARATE | /SHARED]
      [/LOW | /NORMAL | /HIGH | /REALTIME | /ABOVENORMAL | /BELOWNORMAL]
      [/NODE <NUMA node>] [/AFFINITY <hex affinity mask>] [/WAIT] [/B]
      [command/program] [parameters]

    "title"     要在視窗標題列顯示的標題。
    path        開始目錄。
    B           啟動應用程式但不建立新視窗。應用程式會略過 ^C 處理。除非應用
                程式啟用 ^C 處理，否則 ^Break 是唯一可以中斷應用程式的方法。
    I           新環境將會是傳遞給 cmd.exe 的原始環境，而不是目前的環境。
    MIN         啟動時讓視窗最小化。
    MAX         啟動時讓視窗最大化。
    SEPARATE    在不同的記憶體空間啟動 16 位元 Windows 程式。
    SHARED      在共用的記憶體空間啟動 16 位元 Windows 程式。
    LOW         在 IDLE 優先順序類別中啟動應用程式。
    NORMAL      在 NORMAL 優先順序類別中啟動應用程式。
    HIGH        在 HIGH 優先順序類別中啟動應用程式。
    REALTIME    在 REALTIME 優先順序類別中啟動應用程式。
    ABOVENORMAL 在 ABOVENORMAL 優先順序類別中啟動應用程式。
    BELOWNORMAL 在 BELOWNORMAL 優先順序類別中啟動應用程式。
    NODE        以十進位整數指定慣用的非統一記憶體架構 (NUMA) 節點。
    AFFINITY    以十六進位數字指定處理器親和性遮罩。會限制處理程序在這些
                處理器上執行。

                當合併使用 /AFFINITY 及 /NODE 時，親和性遮罩會以不同的方式
                解譯。指定親和性遮罩就如 NUMA 節點的處理器遮罩向右位移，從

**Comment by amorphobia** [comment]
请问你的系统是什么？好像我的和你有一点点区别，比如在 Windows 10 上， `start /help` 会出错：
```
C:\>start /help
Invalid switch - "/help".
```

只能通过 `start /?` 来获取帮助。

另外，我照帮助改为
```
io.popen("start /B calc.exe")
```

依然会有 Command Prompt, 随后才出现计算器。

**Comment by shewer** [comment]
win10 home 
 我的是6年前電腦  可能慢得出不來吧  &^^
start/?    
help start


start  /min

**Comment by amorphobia** [comment]
小鹤音形的直通车都是非常简单的命令，即使等待 `os.execute(cmd)` 结束应该问题也不大…
