### ISSUE TITLE
Windows10 上屏时会崩溃

### ISSUE THREAD

**Issue by Yiklek** [amorphobia/openfly#44]
weasel版本：0.14.3
schema中注释掉`lua_processor@openfly_shortcut_processor`可正常上屏

崩溃时的日志
![image](https://user-images.githubusercontent.com/21033316/136665348-47719cf5-613e-4a94-a08e-7b302d14d665.png)

**Comment by lightyears1998** [comment]
@Yiklek  

我几个月前也遇到了这个问题。后来发现如 @amorphobia  在 README 的[“已知限制”小节](https://github.com/amorphobia/openfly#%E5%B7%B2%E7%9F%A5%E9%99%90%E5%88%B6)中提到的，由于 weasel v0.14.3 的 librime 版本还是太低，需要升级 librime 才能解决这个问题。可以参考 weasel repo 中的这个 [PR](https://github.com/rime/weasel/pull/624)。

我顺手 build 了一份，如果需要可以自取：[weasel-0.14.3.0-installer.zip](https://github.com/amorphobia/openfly/files/7457655/weasel-0.14.3.0-installer.zip)

**Comment by AlseinX** [comment]
这里是Windows 11，用的 @lightyears1998 的编译版本，全是这样的问题：
```
E1105 17:19:46.214826 14660 engine.cc:312] error creating processor: 'lua_processor'
E1105 17:19:46.219827 14660 engine.cc:346] error creating translator: 'lua_translator'
```
不会崩溃，但是所有的Lua就像不存在一样

**Comment by lightyears1998** [comment]
> 
> 
> 这里是Windows 11，用的 @lightyears1998 的编译版本，全是这样的问题：
> 
> ```
> E1105 17:19:46.214826 14660 engine.cc:312] error creating processor: 'lua_processor'
> E1105 17:19:46.219827 14660 engine.cc:346] error creating translator: 'lua_translator'
> ```
> 
> 不会崩溃，但是所有的Lua就像不存在一样

蚌埠住了呀。我我我忘记编译 `librime-lua` 了。这个版本应该就正常了。

[weasel-0.14.3.0-installer.zip](https://github.com/amorphobia/openfly/files/7487000/weasel-0.14.3.0-installer.zip)

**Comment by AlseinX** [comment]
@lightyears1998  OK了
话说我习惯官方版小鹤可以设置的那种让首选直接嵌入在输入的地方，然后候选区隐藏首选，在唯一候选时直接隐藏候选框，这个有办法做到吗

**Comment by lightyears1998** [comment]
> @lightyears1998 OK了 话说我习惯官方版小鹤可以设置的那种让首选直接嵌入在输入的地方，然后候选区隐藏首选，在唯一候选时直接隐藏候选框，这个有办法做到吗

不太清楚。
