### ISSUE TITLE
windows上启用lua process的话会崩溃

### ISSUE THREAD

**Issue by tmbmyeue** [amorphobia/openfly#49]
手动把需要的文件移动到用户目录，并且在rime.lua中加上补丁，启动后打字按上屏就会卡死，过一会之后就只能输英文了，似乎是崩溃了。但是把processor中的lua processor禁用掉后，就能正常打字了，当然短语的命令都没有了。

**Comment by lightyears1998** [comment]
这大概是官网上的小狼毫的 librime 版本太低的缘故，您可以看看 #45 是否能解决这个问题呢。

**Comment by amorphobia** [comment]
@lightyears1998 谢谢帮忙回答

@tmbmyeue 请你看看上面的方式能否解决呢？
